
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    String idKasir;
    
    public FormUtama(String id) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        idKasir = id;
        
        if(idKasir == ""){
            JOptionPane.showMessageDialog(null, "Anda harus login dulu");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProfile = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuKasir = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        menuKendaraan = new javax.swing.JMenuItem();
        menuTeknisi = new javax.swing.JMenuItem();
        menuSukuC = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        laporanTrans = new javax.swing.JMenuItem();
        laporanBarang = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        menuProfile.setText("Profile");
        menuProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProfileMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProfile);

        jMenu1.setText("Master");

        menuKasir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuKasir.setText("Kasir");
        menuKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKasirActionPerformed(evt);
            }
        });
        jMenu1.add(menuKasir);

        menuPelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(menuPelanggan);

        menuKendaraan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuKendaraan.setText("Kendaraan");
        menuKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKendaraanActionPerformed(evt);
            }
        });
        jMenu1.add(menuKendaraan);

        menuTeknisi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuTeknisi.setText("Teknisi");
        menuTeknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTeknisiActionPerformed(evt);
            }
        });
        jMenu1.add(menuTeknisi);

        menuSukuC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuSukuC.setText("Suku Cadang");
        menuSukuC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSukuCActionPerformed(evt);
            }
        });
        jMenu1.add(menuSukuC);

        jMenuBar1.add(jMenu1);

        menuTransaksi.setText("Transaksi");
        menuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTransaksi);

        jMenu5.setText("Laporan");

        laporanTrans.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        laporanTrans.setText("Pendapatan");
        laporanTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanTransMouseClicked(evt);
            }
        });
        laporanTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanTransActionPerformed(evt);
            }
        });
        jMenu5.add(laporanTrans);

        laporanBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        laporanBarang.setText("Barang");
        laporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBarangActionPerformed(evt);
            }
        });
        jMenu5.add(laporanBarang);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Logout");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKasirActionPerformed
        FormKasir fk = new FormKasir();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(fk);
        fk.setLocation((jDesktopPane1.getWidth()-fk.getWidth())/2, (jDesktopPane1.getHeight()-fk.getHeight())/2);
        fk.setVisible(true);
    }//GEN-LAST:event_menuKasirActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        FormPelanggan fp = new FormPelanggan();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(fp);
        fp.setLocation((jDesktopPane1.getWidth()-fp.getWidth())/2, (jDesktopPane1.getHeight()-fp.getHeight())/2);
        fp.setVisible(true);
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProfileMouseClicked
        // TODO add your handling code here:
        FormProfile fp = new FormProfile(idKasir);
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(fp);
        fp.setLocation((jDesktopPane1.getWidth()-fp.getWidth())/2, (jDesktopPane1.getHeight()-fp.getHeight())/2);
        fp.setVisible(true);
    }//GEN-LAST:event_menuProfileMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        FormLogin fl = new FormLogin();
        fl.setLocation((jDesktopPane1.getWidth()-fl.getWidth())/2, (jDesktopPane1.getHeight()-fl.getHeight())/2);
        fl.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void menuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseClicked
        // TODO add your handling code here:
        FormTransaksi ft = new FormTransaksi(idKasir);
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(ft);
        ft.setLocation((jDesktopPane1.getWidth()-ft.getWidth())/2, (jDesktopPane1.getHeight()-ft.getHeight())/2);
        ft.setVisible(true);
    }//GEN-LAST:event_menuTransaksiMouseClicked

    private void menuKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKendaraanActionPerformed
        // TODO add your handling code here:
        FormKendaraan fk = new FormKendaraan();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(fk);
        fk.setLocation((jDesktopPane1.getWidth()-fk.getWidth())/2, (jDesktopPane1.getHeight()-fk.getHeight())/2);
        fk.setVisible(true);
    }//GEN-LAST:event_menuKendaraanActionPerformed

    private void menuTeknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTeknisiActionPerformed
        // TODO add your handling code here:
        FormTeknisi ft = new FormTeknisi();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(ft);
        ft.setLocation((jDesktopPane1.getWidth()-ft.getWidth())/2, (jDesktopPane1.getHeight()-ft.getHeight())/2);
        ft.setVisible(true);
    }//GEN-LAST:event_menuTeknisiActionPerformed

    private void menuSukuCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSukuCActionPerformed
        // TODO add your handling code here:
        FormSuku fs = new FormSuku();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(fs);
        fs.setLocation((jDesktopPane1.getWidth()-fs.getWidth())/2, (jDesktopPane1.getHeight()-fs.getHeight())/2);
        fs.setVisible(true);
    }//GEN-LAST:event_menuSukuCActionPerformed

    private void laporanTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanTransMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_laporanTransMouseClicked

    private void laporanTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanTransActionPerformed
        // TODO add your handling code here:
        FormTrans ft = new FormTrans();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(ft);
        ft.setLocation((jDesktopPane1.getWidth()-ft.getWidth())/2, (jDesktopPane1.getHeight()-ft.getHeight())/2);
        ft.setVisible(true);
    }//GEN-LAST:event_laporanTransActionPerformed

    private void laporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBarangActionPerformed
        // TODO add your handling code here:
        FormBarang fb = new FormBarang();
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(fb);
        fb.setLocation((jDesktopPane1.getWidth()-fb.getWidth())/2, (jDesktopPane1.getHeight()-fb.getHeight())/2);
        fb.setVisible(true);
    }//GEN-LAST:event_laporanBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem laporanBarang;
    private javax.swing.JMenuItem laporanTrans;
    private javax.swing.JMenuItem menuKasir;
    private javax.swing.JMenuItem menuKendaraan;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenuItem menuSukuC;
    private javax.swing.JMenuItem menuTeknisi;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
