/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FormPelanggan extends javax.swing.JInternalFrame {
    static Connection conn;
    static Statement stat = null;
    static ResultSet rset = null;
    static PreparedStatement pstat;
    static CallableStatement cstat;
    static String query;
    DefaultTableModel modelPel = new DefaultTableModel
    (new Object[] {"Id","Nama","No HP", "Alamat", "Tgl Daftar", "Keluhan"}, 0);
    
    
    public FormPelanggan() {
        initComponents();
        tbPelanggan.setModel(modelPel);
        koneksi();
        read();
        genNewId();
    }
    
    public void koneksi() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection
            ("jdbc:oracle:thin:@localhost:1521:XE", "BENGKEL", "BENGKEL");
            System.out.println("Koneksi database sukses");
        } catch (Exception ex) {
            System.out.println
            ("Terjadi kesalahan: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        tfAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfKeluhan = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPelanggan = new javax.swing.JTable();
        tfCari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul.setText("Master Pelanggan");

        jLabel1.setText("ID");

        tfId.setText("P000");

        jLabel3.setText("No. HP");

        jLabel2.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Tgl Daftar");

        tgl.setDateFormatString("dd-MMM-yyyy");

        jLabel6.setText("Keluhan");

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        tbPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No. HP", "Alamat", "Tgl Daftar", "Keluhan"
            }
        ));
        tbPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPelanggan);

        jButton2.setText("Cari");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelJudul)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKeluhan)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(reset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tambah))
                                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfAlamat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNo, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(tfNama)
                            .addComponent(tfId))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapus)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(tambah)
                    .addComponent(ubah)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Master Pelanggan", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        // TODO add your handling code here:
        try
        {
            query = "{call simpanPelanggan(?,?,?,?,?)}";
            pstat = conn.prepareStatement(query);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String date = sdf.format(tgl.getDate());
            
            pstat.setString(1, tfNama.getText());
            pstat.setString(2, tfNo.getText());
            pstat.setString(3, tfAlamat.getText());
            pstat.setString(4, date);
            pstat.setString(5, tfKeluhan.getText());
            
            System.out.println(date);
            
            int jum = pstat.executeUpdate();
            if (jum > 0) {
                 JOptionPane.showMessageDialog(null, "Data pelanggan berhasil disimpan");
                 reset();
            } else {
                JOptionPane.showMessageDialog(null, "Tdk ada data pelanggan yg disimpan");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan");
        }
        read();
        genNewId();
        reset();
    }//GEN-LAST:event_tambahMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetMouseClicked

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
        // TODO add your handling code here:
        try{
            query = "update pelanggan set nama_pelanggan=?, "
                    + "no_hppelanggan=?, "
                    + "alamat_pelanggan=?, "
                    + "tgl_daftar=?, "
                    + "keluhan=? where id_pelanggan=?";
            pstat = conn.prepareStatement(query);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String date = sdf.format(tgl.getDate());
            
            pstat.setString(6, tfId.getText());
            pstat.setString(1, tfNama.getText());
            pstat.setString(2, tfNo.getText());
            pstat.setString(3, tfAlamat.getText());
            pstat.setString(4, date);
            pstat.setString(5, tfKeluhan.getText());
            
            int jum = pstat.executeUpdate();
            if (jum > 0) {
                 JOptionPane.showMessageDialog(null, "Data pelanggan berhasil diubah");
                 reset();
            } else {
                JOptionPane.showMessageDialog(null, "Tdk ada data pelanggan yg diubah");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        read();
        genNewId();
        reset();
    }//GEN-LAST:event_ubahMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        try{
            query = "delete from pelanggan where id_pelanggan=?";
            pstat = conn.prepareStatement(query);
            pstat.setString(1, tfId.getText());
            
            int jum = pstat.executeUpdate();
            if (jum > 0) {
                 JOptionPane.showMessageDialog(null, "Data pelanggan berhasil dihapus");
                 reset();
            } else {
                JOptionPane.showMessageDialog(null, "Tdk ada data pelanggan yg dihapus");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        read();
        genNewId();
        reset();
    }//GEN-LAST:event_hapusMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_jButton2MouseClicked

    private void tbPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPelangganMouseClicked
        // TODO add your handling code here:
        int baris = tbPelanggan.getSelectedRow();
        String id = tbPelanggan.getModel().getValueAt(baris, 0).toString();
        String nama = tbPelanggan.getModel().getValueAt(baris, 1).toString();
        String nohp = tbPelanggan.getModel().getValueAt(baris, 2).toString();
        String alamat = tbPelanggan.getModel().getValueAt(baris, 3).toString();
        String tglDaf = tbPelanggan.getModel().getValueAt(baris, 4).toString();
        String keluhan = tbPelanggan.getModel().getValueAt(baris, 5).toString();
        
        tfId.setText(id);
        tfNama.setText(nama);
        tfNo.setText(nohp);
        tfAlamat.setText(alamat);
        tfKeluhan.setText(keluhan);
        
        String tglStr = tglDaf.split(" ", 2)[0];  
        java.util.Date date1;  
        try {
            date1 = (java.util.Date) new SimpleDateFormat("yyyy-MM-dd").parse(tglStr);
            tgl.setDate(date1);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_tbPelangganMouseClicked

        void genNewId(){
        try {
            query = query = "select generateIdPel() from dual";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            
            while (rset.next()) { 
                String id = rset.getString(1);
                
                tfId.setText(id);
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }
    
    void read() {
        try {
            query = query = "select * from pelanggan "
                    + "where lower(id_pelanggan) like '%" + tfCari.getText().toLowerCase()  + "%' or "
                    + "lower(nama_pelanggan) like '%" + tfCari.getText().toLowerCase() + "%' or "
                    + "lower(alamat_pelanggan) like '%" + tfCari.getText().toLowerCase() + "%' or "
                    + "lower(keluhan) like '%" + tfCari.getText().toLowerCase() + "%' "
                    + "order by 1 desc";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            modelPel.setRowCount(0); //clear data di jtable
            
            while (rset.next()) { //lopping selama ada baris data
                Vector data = new Vector();
                data.add(rset.getString(1));
                data.add(rset.getString(2));
                data.add(rset.getString(3));
                data.add(rset.getString(4));
                data.add(rset.getString(5));
                data.add(rset.getString(6));
                modelPel.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void reset(){
        tfId.setText("");
        tfNama.setText("");
        tfNo.setText("");
        tfAlamat.setText("");
        tgl.setDate(null);
        tfKeluhan.setText("");
        genNewId();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JButton reset;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbPelanggan;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfCari;
    private javax.swing.JLabel tfId;
    private javax.swing.JTextField tfKeluhan;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNo;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
