/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.BorderLayout;
import static java.lang.Integer.parseInt;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
public class FormTransaksi extends javax.swing.JInternalFrame {
    static Connection conn;
    static Statement stat = null;
    static ResultSet rset = null;
    static PreparedStatement pstat;
    static CallableStatement cstat;
    static String query;
    int totalBayar = 0;
    String idTeknisi = null;
    int hargaTek = 0;
    String idServ = null;
    String idKasir;
    String arraySpare[];
    int baris;
    DefaultTableModel modelTran = new DefaultTableModel
    (new Object[] {"No. Tag", "No. Pol", "Merk", "Nama", "Tgl", "Total", "Bayar", "Kembalian"}, 0);
    
    
    public FormTransaksi(String idKas) {
        initComponents();
        tbTransaksi.setModel(modelTran);
        idKasir = idKas;
        tbSp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Id", "Nama", "Jumlah", "Harga", "Total"
            }
            ));
        koneksi();
        read();
        isiSparePart();
        isiNamaTek();
        isiNamaPel();
        hitungBayar(0, 0);
        reset();
    }
    
    public void koneksi() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection
            ("jdbc:oracle:thin:@localhost:1521:XE", "BENGKEL", "BENGKEL");
            System.out.println("Koneksi database sukses");
        } catch (Exception ex) {
            System.out.println
            ("Terjadi kesalahan: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateRep = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        labelJudul1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbNamaSp = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        spJml = new javax.swing.JSpinner();
        btTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSp = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lbTotalHarga = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbMetode = new javax.swing.JComboBox<>();
        btSimpan = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        pelangganOk = new javax.swing.JButton();
        cbNoPol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lbHargaTek = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbKembalian = new javax.swing.JLabel();
        spBayar = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        cbNamaTek = new javax.swing.JComboBox<>();
        teknisiOk = new javax.swing.JButton();
        cbNamaPel = new javax.swing.JComboBox<>();
        btCetak = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTransaksi = new javax.swing.JTable();
        btCetak1 = new javax.swing.JButton();

        setClosable(true);

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul.setText("Transaksi");

        jLabel1.setText("Nama Pelanggan");

        jLabel4.setText("No. Polisi");

        jLabel5.setText("Tgl. Reparasi");

        dateRep.setDateFormatString("dd-MMM-yyyy");

        jLabel2.setText("Nama Teknisi");

        labelJudul1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul1.setText("Spare Part");

        jLabel3.setText("Nama");

        cbNamaSp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Jumlah");

        btTambah.setText("Tambah");
        btTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTambahMouseClicked(evt);
            }
        });

        tbSp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Jumlah", "Harga", "Total"
            }
        ));
        tbSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSp);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Total Harga :");

        lbTotalHarga.setText("0");

        jLabel13.setText("Metode Pembayaran : ");

        cbMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai" }));

        btSimpan.setText("Simpan");
        btSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSimpanMouseClicked(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btResetMouseClicked(evt);
            }
        });

        pelangganOk.setText("OK");
        pelangganOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelangganOkMouseClicked(evt);
            }
        });

        jLabel6.setText("Harga Teknisi");

        lbHargaTek.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bayar          :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Kembalian   :");

        lbKembalian.setText("0");

        jButton1.setText("Hitung");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btHapus.setText("Hapus");
        btHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHapusMouseClicked(evt);
            }
        });

        cbNamaTek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        teknisiOk.setText("OK");
        teknisiOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teknisiOkMouseClicked(evt);
            }
        });

        cbNamaPel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btCetak.setText("Cetak");
        btCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCetakMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbNamaSp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spJml, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btHapus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNoPol, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbNamaPel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pelangganOk)))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(dateRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbHargaTek)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbNamaTek, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(teknisiOk))))))
                            .addComponent(labelJudul)
                            .addComponent(labelJudul1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(spBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbTotalHarga)
                                        .addGap(179, 179, 179)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbKembalian)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReset)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(pelangganOk)
                            .addComponent(cbNamaPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbNoPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(labelJudul1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbNamaTek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teknisiOk))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lbHargaTek))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbNamaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTambah)
                    .addComponent(btHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbTotalHarga)
                    .addComponent(jLabel13)
                    .addComponent(cbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbKembalian))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSimpan)
                        .addComponent(btCetak)
                        .addComponent(btReset))
                    .addComponent(jButton1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi", jPanel1);

        tbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Tag", "Nama Pel", "No. Pol", "Tgl", "Total"
            }
        ));
        jScrollPane2.setViewportView(tbTransaksi);

        btCetak1.setText("Cetak");
        btCetak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCetak1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCetak1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btCetak1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Transaksi", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teknisiOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teknisiOkMouseClicked
        // TODO add your handling code here:
        try {
            System.out.println(cbNamaTek.getSelectedItem());
            query = query = "select * from teknisi where nama_teknisi='" + cbNamaTek.getSelectedItem() + "'";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);

            if (rset.next()) {
                String id = null;
                id = rset.getString(1);
                int harga = rset.getInt(5);

                if(!id.equals(null)) {
                    idTeknisi = id;
                    hargaTek = harga;

                    lbHargaTek.setText("" +harga);
                }
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_teknisiOkMouseClicked

    private void btHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHapusMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) tbSp.getModel();

        if(tbSp.getSelectedRowCount() == 1){
            int totalSp = (int) tbSp.getValueAt(baris, 4);

            hitungBayar(0, totalSp);

            tbModel.removeRow(tbSp.getSelectedRow());
        } else {
            if(tbSp.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tabel Kosong");
            }
        }
        read();
    }//GEN-LAST:event_btHapusMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int kembali = (int) spBayar.getValue() - Integer.parseInt(lbTotalHarga.getText());

        if(kembali < 0) {
            JOptionPane.showMessageDialog(null, "Uang kurang");
        } else {
            lbKembalian.setText("" +kembali);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void pelangganOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelangganOkMouseClicked
        // TODO add your handling code here:
        try {
            query = "select * from pelanggan where nama_pelanggan='" + cbNamaPel.getSelectedItem() + "'";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);

            if (rset.next()) {
                String id = rset.getString(1);

                if(!id.equals(null)) {
                    isiNoPol(id);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nama pelanggan tidak ditemukan");
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_pelangganOkMouseClicked

    private void btResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btResetMouseClicked

    private void btSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSimpanMouseClicked
        // TODO add your handling code here:
        if((int) spBayar.getValue() >= Integer.parseInt(lbTotalHarga.getText())){
            
            try {
                for(int i = 0; i < tbSp.getRowCount(); i++){
                query = "select stok from suku_cadang where id_sukucadang = '" + tbSp.getValueAt(i, 0).toString() + "'";
                stat = conn.createStatement();
                rset = stat.executeQuery(query);
                
                while (rset.next()) {
                    int stok = rset.getInt(1);
                    
                    if(stok <= 0) {
                        JOptionPane.showMessageDialog(null, "Stok sparepart kosong");
                        return;
                    }
                }
            }
            } catch ( Exception e ){
                System.out.println(e);
            }
            
            tambahServ();
            tambahTagih();
            tambahSukuServ();
        } else {
            JOptionPane.showMessageDialog(null, "Simpan transaksi gagal");
        }
        read();
    }//GEN-LAST:event_btSimpanMouseClicked

    private void tbSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSpMouseClicked
        // TODO add your handling code here:
        baris = tbSp.getSelectedRow();
        String nama = tbSp.getModel().getValueAt(baris, 1).toString();
        int jml = (int) tbSp.getModel().getValueAt(baris, 2);

        cbNamaSp.setSelectedItem(nama);
        spJml.setValue(jml);
    }//GEN-LAST:event_tbSpMouseClicked

    private void btTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTambahMouseClicked
        // TODO add your handling code here:
        try {
            query = query = "select * from suku_cadang where nama_sukucadang='" + cbNamaSp.getSelectedItem() + "'";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            DefaultTableModel dataModel = (DefaultTableModel) tbSp.getModel();
            
            if(dataModel.getRowCount() > 0){
                for (int i = dataModel.getRowCount() - 1; i >= 0; i--) {
                    if(cbNamaSp.getSelectedItem() == dataModel.getValueAt(i, 1)){
                        int jumlah = (int) dataModel.getValueAt(i, 2) + (int) spJml.getValue();
                        int hargaLama = (int) dataModel.getValueAt(i, 3);
                        int totalLama = (int) dataModel.getValueAt(i, 4);
                        int total = hargaLama*jumlah;
                        
                        dataModel.setValueAt(jumlah, i, 2);
                        dataModel.setValueAt(total, i, 4);
                        hitungBayar(total - totalLama, 0);
                        return;
                    } 
                }
            }
            
            while (rset.next()) { //lopping selama ada baris data
                String id = rset.getString(1);
                int harga = (int) rset.getInt(4);
                int total = harga * (int) spJml.getValue();
                hitungBayar(total, 0);

                List data = new ArrayList();
                data.add(id);
                data.add(cbNamaSp.getSelectedItem());
                data.add(spJml.getValue());
                data.add(harga);
                data.add(total);
                dataModel.addRow(data.toArray());

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btTambahMouseClicked

    private void btCetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCetakMouseClicked
        // TODO add your handling code here:
        try {
            query = query = "select max(no_tagihan) from tagihan";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            String id = "";
            
            if(rset.next()){
                id = rset.getString(1);
            }
            
            Map <String, Object> mapParam = new HashMap<String, Object>();
            mapParam.put("no_tag", id);
            
            JasperPrint jp = JasperFillManager.fillReport
            (getClass().getResourceAsStream("notaTransaksi.jasper"), mapParam, conn);
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btCetakMouseClicked

    private void btCetak1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCetak1MouseClicked
        // TODO add your handling code here:
        try {
        int baris = tbTransaksi.getSelectedRow();
        String id = tbTransaksi.getModel().getValueAt(baris, 0).toString();
        
        Map <String, Object> mapParam = new HashMap<String, Object>();
            mapParam.put("no_tag", id);
            
            JasperPrint jp = JasperFillManager.fillReport
            (getClass().getResourceAsStream("notaTransaksi.jasper"), mapParam, conn);
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btCetak1MouseClicked

    void tambahServ(){
        try
        {
            query = "insert into service values (?,?,?,?)";
            pstat = conn.prepareStatement(query);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String date = sdf.format(dateRep.getDate());
            idServ = genIdServ();

            pstat.setString(1, idServ);
            pstat.setString(2, idTeknisi);
            pstat.setString(3, cbNoPol.getSelectedItem().toString());
            pstat.setString(4, date);

            int jum = pstat.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Data Service ditambahkan");
            } 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Service gagal ditambahkan");
        }
    }
    
    void tambahTagih(){
        try
        {
            query = "insert into tagihan values (?,?,?,?,?,?,?,?)";
            pstat = conn.prepareStatement(query);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String date = sdf.format(dateRep.getDate());
            String idTag = genIdTag();

            pstat.setString(1, idTag);
            pstat.setString(2, idServ);
            pstat.setString(3, idKasir);
            pstat.setString(4, date);
            pstat.setInt(5, Integer.parseInt(lbTotalHarga.getText()));
            pstat.setString(6, cbMetode.getSelectedItem().toString());
            pstat.setInt(7, (int) spBayar.getValue());
            pstat.setInt(8, Integer.parseInt(lbKembalian.getText()));

            int jum = pstat.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Data Tagihan ditambahkan");
            } 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Tagihan gagal ditambahkan");
        }
    }
    
    void tambahSukuServ(){
        try
        {
            for(int i = 0; i < tbSp.getRowCount(); i++){
                query = "insert into suku_cadang_service values (?,?,?,?,?)";
                pstat = conn.prepareStatement(query);
            
                pstat.setString(1, idServ);
                pstat.setString(2, tbSp.getValueAt(i, 0).toString());
                pstat.setInt(3, (int) tbSp.getValueAt(i, 2));
                pstat.setInt(4, (int) tbSp.getValueAt(i, 3));
                pstat.setInt(5, (int) tbSp.getValueAt(i, 4));
                
                pstat.executeUpdate();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Suku Service gagal ditambahkan");
        }
    }
    
    String genIdServ(){
        String id = null;
        
        try {
            query = query = "select generateidserv() from dual";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            
            while (rset.next()) { 
                id = rset.getString(1);
            }
        } catch(Exception e){
            System.out.println(e);
        }
        
        return id;
    }
    
    String genIdTag(){
        String id = null;
        
        try {
            query = query = "select generateIdtag() from dual";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            
            while (rset.next()) { 
                id = rset.getString(1);
            }
        } catch(Exception e){
            System.out.println(e);
        }
        
        return id;
    }
    
    void isiSparePart() {
        try {
            query = "select nama_sukucadang from suku_cadang";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            cbNamaSp.removeAllItems(); //clear data di combo
            
            cbNamaSp.addItem("==Sparepart==");
            while (rset.next()) { //lopping selama ada baris data
                cbNamaSp.addItem (rset.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void isiNamaTek() {
        try {
            query = "select nama_teknisi from teknisi";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            cbNamaTek.removeAllItems(); //clear data di combo
            
            cbNamaTek.addItem("==Teknisi==");
            while (rset.next()) { //lopping selama ada baris data
                cbNamaTek.addItem(rset.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void isiNamaPel() {
        try {
            query = "select nama_pelanggan from pelanggan";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            cbNamaPel.removeAllItems(); //clear data di combo
            
            cbNamaPel.addItem("==Pelanggan==");
            while (rset.next()) { //lopping selama ada baris data
                cbNamaPel.addItem(rset.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void isiNoPol(String idPel) {
        try {
            query = "select no_pol from kendaraan where id_pelanggan='" + idPel + "'";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            cbNoPol.removeAllItems(); //clear data di combo
            
            while (rset.next()) { //lopping selama ada baris data
                cbNoPol.addItem (rset.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void hitungBayar(int total, int kurang){
        totalBayar += total;
        totalBayar -= kurang;
        
        lbTotalHarga.setText("" + (totalBayar + hargaTek));
    }
    
    void read() {
        try {
            query = "select t.no_tagihan, s.no_pol, k.merk_motor, p.nama_pelanggan, t.tanggal_reparasi, t.total_hargaservice, t.bayar, t.kembalian " +
                    "from tagihan t, service s, kendaraan k, pelanggan p " +
                    "where t.id_service = s.id_service and s.no_pol = k.no_pol and k.id_pelanggan = p.id_pelanggan " +
                    "order by 1";
            
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            modelTran.setRowCount(0); //clear data di jtable
            
            while (rset.next()) { //lopping selama ada baris data
                Vector data = new Vector();
                data.add(rset.getString(1));
                data.add(rset.getString(2));
                data.add(rset.getString(3));
                data.add(rset.getString(4));
                data.add(rset.getString(5));
                data.add(rset.getString(6));
                data.add(rset.getString(7));
                data.add(rset.getString(8));
                modelTran.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void reset(){
        DefaultTableModel tbModel = (DefaultTableModel) tbSp.getModel();
        
        int rowCount = tbModel.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            tbModel.removeRow(i);
        }
        
        cbNamaPel.setSelectedIndex(0);
        cbNoPol.removeAllItems();
        cbNamaTek.setSelectedIndex(0);
        lbHargaTek.setText("" +0);
        cbNamaSp.setSelectedIndex(0);
        spJml.setValue(1);
        lbTotalHarga.setText("" +0);
        cbMetode.setSelectedIndex(0);
        dateRep.setDate(null);
        spBayar.setValue(0);
        lbKembalian.setText("" +0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCetak;
    private javax.swing.JButton btCetak1;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTambah;
    private javax.swing.JComboBox<String> cbMetode;
    private javax.swing.JComboBox<String> cbNamaPel;
    private javax.swing.JComboBox<String> cbNamaSp;
    private javax.swing.JComboBox<String> cbNamaTek;
    private javax.swing.JComboBox<String> cbNoPol;
    private com.toedter.calendar.JDateChooser dateRep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudul1;
    private javax.swing.JLabel lbHargaTek;
    private javax.swing.JLabel lbKembalian;
    private javax.swing.JLabel lbTotalHarga;
    private javax.swing.JButton pelangganOk;
    private javax.swing.JSpinner spBayar;
    private javax.swing.JSpinner spJml;
    private javax.swing.JTable tbSp;
    private javax.swing.JTable tbTransaksi;
    private javax.swing.JButton teknisiOk;
    // End of variables declaration//GEN-END:variables
}
