/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import static java.lang.Integer.parseInt;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FormKendaraan extends javax.swing.JInternalFrame {
    static Connection conn;
    static Statement stat = null;
    static ResultSet rset = null;
    static PreparedStatement pstat;
    static CallableStatement cstat;
    static String query, query2;
    DefaultTableModel modelKen = new DefaultTableModel
    (new Object[] {"No Pol","Nama","Jenis", "Merk"}, 0);
    
    
    public FormKendaraan() {
        initComponents();
        tbKendaraan.setModel(modelKen);
        koneksi();
        read();
        isiNamaPel();
    }
    
    public void koneksi() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection
            ("jdbc:oracle:thin:@localhost:1521:XE", "BENGKEL", "BENGKEL");
            System.out.println("Koneksi database sukses");
        } catch (Exception ex) {
            System.out.println
            ("Terjadi kesalahan: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKendaraan = new javax.swing.JTable();
        btCari = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMerk = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        tfNo = new javax.swing.JTextField();
        cbNama = new javax.swing.JComboBox<>();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(492, 602));

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudul.setText("Master Kendaraan");

        jLabel1.setText("No. Polisi");

        jLabel3.setText("Jenis Motor");

        jLabel2.setText("Nama");

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        tbKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Pol", "Nama", "Jenis", "Merk"
            }
        ));
        tbKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKendaraanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKendaraan);

        btCari.setText("Cari");
        btCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCariMouseClicked(evt);
            }
        });

        jLabel4.setText("Merk Motor");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standart", "Bebek", "Sport", "Trail", "Skuter" }));

        cbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Pelanggan==", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCari)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudul)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(tambah)
                    .addComponent(ubah)
                    .addComponent(hapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCari)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Master Kendaraan", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCariMouseClicked
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btCariMouseClicked

    private void tbKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKendaraanMouseClicked
        // TODO add your handling code here:
        int baris = tbKendaraan.getSelectedRow();
        String no = tbKendaraan.getModel().getValueAt(baris, 0).toString();
        String nama = tbKendaraan.getModel().getValueAt(baris, 1).toString();
        String jenis = tbKendaraan.getModel().getValueAt(baris, 2).toString();
        String merk = tbKendaraan.getModel().getValueAt(baris, 3).toString();
        
        tfNo.setText(no);
        cbNama.setSelectedItem(nama);
        cbJenis.setSelectedItem(jenis);
        tfMerk.setText(merk);
    }//GEN-LAST:event_tbKendaraanMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        try{
            query = "delete from kendaraan where no_pol=?";
            pstat = conn.prepareStatement(query);
            pstat.setString(1, tfNo.getText());

            int jum = pstat.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Data kendaraan berhasil dihapus");
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Tdk ada data kendaraan yg dihapus");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        read();
        reset();
    }//GEN-LAST:event_hapusMouseClicked

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
        // TODO add your handling code here:
        try{
            int baris = tbKendaraan.getSelectedRow();
            String no = tbKendaraan.getModel().getValueAt(baris, 0).toString();
            
            query = "update kendaraan set jenis_motor=?, "
            + "merk_motor=?, "
            + "no_pol=? "
            + "where no_pol=?";
            pstat = conn.prepareStatement(query);

            pstat.setString(4, no);
            pstat.setString(1, cbJenis.getSelectedItem().toString());
            pstat.setString(2, tfMerk.getText());
            pstat.setString(3, tfNo.getText());

            int jum = pstat.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Data kasir berhasil diubah");
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Tdk ada data kasir yg diubah");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        read();
        reset();
    }//GEN-LAST:event_ubahMouseClicked

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        // TODO add your handling code here:
        try
        {
            query = "insert into kendaraan values (?,?,?,?)";
            pstat = conn.prepareStatement(query);
            System.out.println("OKKK");
            query2 = "select * from pelanggan where nama_pelanggan='" + cbNama.getSelectedItem() + "'";
            System.out.println(query2);
            stat = conn.createStatement();
            rset = stat.executeQuery(query2);
            String idPel = "";
            
            while (rset.next()) {
                idPel = rset.getString(1);
            }

            pstat.setString(1, tfNo.getText());
            pstat.setString(2, idPel);
            pstat.setString(3, cbJenis.getSelectedItem().toString());
            pstat.setString(4, tfMerk.getText());

            int jum = pstat.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Data kasir berhasil disimpan");
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Tdk ada data kasir yg disimpan");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan");
        }
        read();
        reset();
    }//GEN-LAST:event_tambahMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetMouseClicked
    
    void read() {
        try {
            query = "select k.no_pol, p.nama_pelanggan, k.jenis_motor, k.merk_motor " +
                    "from kendaraan k join pelanggan p on k.id_pelanggan = p.id_pelanggan " +
                    "where lower(k.no_pol) like '%" + tfCari.getText().toLowerCase()  + "%' or " +
                    "lower(p.nama_pelanggan) like '%" + tfCari.getText().toLowerCase()  + "%' or " +
                    "lower(k.jenis_motor) like '%" + tfCari.getText().toLowerCase()  + "%' or " +
                    "lower(k.merk_motor) like '%" + tfCari.getText().toLowerCase() + "%' ";
                    
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            modelKen.setRowCount(0); //clear data di jtable
            
            while (rset.next()) { //lopping selama ada baris data
                Vector data = new Vector();
                data.add(rset.getString(1));
                data.add(rset.getString(2));
                data.add(rset.getString(3));
                data.add(rset.getString(4));
                modelKen.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void isiNamaPel() {
        try {
            query = "select nama_pelanggan from pelanggan";
            stat = conn.createStatement();
            rset = stat.executeQuery(query);
            cbNama.removeAllItems(); //clear data di combo
            
            cbNama.addItem("==Pelanggan==");
            while (rset.next()) { //lopping selama ada baris data
                cbNama.addItem (rset.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    void reset(){
        tfNo.setText("");
        cbNama.setSelectedIndex(0);
        cbJenis.setSelectedIndex(0);
        tfMerk.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbNama;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JButton reset;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbKendaraan;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfMerk;
    private javax.swing.JTextField tfNo;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
